# Generated by Django 4.2.4 on 2023-09-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
